### ISSUE TITLE
Rename to groovy-katas

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/groovy-kata#1]
We would like consistency in our repositories:
groovy-katas
gradle-katas
docker-katas
git-katas

**Comment by sofusalbertsen** [comment]
Just renamed it now.
Need to go through all slides and absolute refs and change.
Will you do that at some point @praqma-thi  ?
Then I'll take artifactory

**Comment by praqma-thi** [comment]
Updated the slide deck to go with the change
