### ISSUE TITLE
File basic is left out.

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/groovy-kata#4]
It goes closure basic -> intermediate instead og closure basic -> file basic

**Comment by praqma-thi** [comment]
closures basic -> collections intermediate (you need some closure knowledge for intermediate collections)
collections intermediate -> collections advanced (mostly grepping collections, not a big step up from intermediate)
collections advanced -> file basic

I'll go over the katas and take a note of what the knowledge they depend on

**Comment by praqma-thi** [comment]
it's a bit odd to go into advanced on some topics without covering basics elsewhere

**Comment by sofusalbertsen** [comment]
Ahh sorry okay my bad...
There was just a flow of basic -> basic etc..
But it seams like you have a flow so just stick to it :)

**Comment by praqma-thi** [comment]
Doesn't mean it can't be improved. it's a bit arbitrary at points
